# Generated by Django 3.2.2 on 2021-07-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Author', models.CharField(max_length=60)),
                ('Pages', models.IntegerField()),
                ('Cost', models.FloatField()),
            ],
        ),
    ]
